Absenteeism/urls.py
from django.urls import path
from Absenteeism import views
from django.contrib.auth.views import login,logout

urlpatterns = [
    #path('result/',views.result,name='result'),
    path('login/',login,{'template_name':'Absenteeism/login.html'},name='login'),
    path('logout/',logout,{'template_name':'Absenteeism/logout.html'}),
    path('register/',views.register,name='register'),
    path('profile/',views.profile,name='profile'),
    path('profile/check/',views.check,name='check'),
    path('home/',views.home,name='home'),
    path('all_attendance',views.all_att),
    
]

MIS_Project/urls.py
from django.contrib import admin
from django.urls import path,include
from MIS_Project import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Absenteeism.urls')),
    path('',include('leave_calendar.urls')),
    path('',include('scale_matrix.urls')),
    path('',include('Operator_window.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.MEDIA_ROOT)

leave_calendar/urls.py
from django.urls import path
from leave_calendar import views
from django.contrib.auth.views import login,logout

urlpatterns=[
    path('leave/',views.apply),
    path('get/',views.nun,name='get'),
    path('suggest/',views.suggest,name='leave_suggestion'),
    path('grant/',views.grant,name='grant'),
]

leave_calendar/models.py
from django.db import models
from django.contrib.auth.models import User
from Absenteeism.models import Employee
# Create your models here.
ch=[
    ('medical leave','medical leave'),
    ('casual leave','casual leave'),
    ('formal leave','formal leave'),
]

class LeavePercentage(models.Model):
    leave_percent=models.IntegerField()

    def __str__(self):
        return str(self.leave_percent)

class LeaveApplication(models.Model):

    start_date=models.DateField()
    end_date=models.DateField()
    leave_reason=models.TextField()
    leave_category=models.CharField(choices=ch,max_length=30)
    leave_percnt=models.ForeignKey(LeavePercentage,on_delete=models.CASCADE,null=True)
    no_of_days=models.IntegerField(null=True)
    key=models.ForeignKey(Employee,on_delete=models.CASCADE,null=True,blank=True)
    leave_id=models.IntegerField()


    def __str___(self):
        return str(self.key.user)

leave_calendar/forms.py
from django import forms
from django.forms import ModelForm



from .models import LeaveApplication



class LeaveApplicationForm(ModelForm):

    class Meta:
        model = LeaveApplication
        fields = ('leave_id','start_date', 'end_date', 'leave_category','leave_reason' )
    '''
    def save(self, request, commit=True):
        model = super(LeaveApplicationForm, self).save(commit=False)

        model.usr = request.user.username

        if commit:
            model.save()

        return model
    '''
    def clean_end_date(self):
        start_date = self.cleaned_data['start_date']
        end_date = self.cleaned_data['end_date']
        if end_date >= start_date:
            return end_date
        else:
            raise forms.ValidationError("'End Date' should be "
                                        "after 'Start Date' .")

leave_calendar/views.py
from django.shortcuts import render
from .models import LeaveApplication
from Absenteeism.models import User
from django.urls import reverse
from .forms import LeaveApplicationForm
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from Absenteeism.models import Employee,Person
from django.http import HttpResponse
import datetime
from .models import LeavePercentage

# Create your views here.

@login_required
def apply(request):
    if (request.method=="POST"):
        form = LeaveApplicationForm(data=request.POST or None)
        if form.is_valid():
            value=form.save(commit=False)
            n=request.user.id
            value.key=Employee.objects.get(user=n)
            value.save()
            return redirect('/get')
        else:
             messages.error(request,"Error")
        current_user = ''
        if request.user.is_authenticated:
         current_user = User.objects.get(user=request.user)
        return render(request, 'leave_calendar/detail.html',
                  {'form': form, 'current_user': current_user}, )
    else:
        form=LeaveApplicationForm()
    e=Employee.objects.get(user=request.user)
    args = {'form': form , 'e':e}
    return render(request, 'leave_calendar/index.html', args)

def fun():
    currdate=(datetime.datetime.now()).date()
    #currdate=currdate[:10]
    b=LeaveApplication.objects.all()
    for i in b:
        if(i.end_date<=currdate):
            le=LeaveApplication.objects.get(id=i.id)
            le.key=None
            print("hi")
            le.save()
                #le=LeaveApplication.objects.get(key=n)
                #print(le)
                #le.key.desig=None
                #le.save()

#global variable
global userid
@login_required
def nun(request):
    fun()
    a=Employee.objects.all()
    l=[i.desig for i in a]
    k=[i.user.username for i in a]
    for j in k:
        if (j==request.user.username):
            #variable=j
            indexvalue=k.index(j)
    #if variable in k:
        #indexvalue=k.index(variable)
    n=l[indexvalue]
    print(n)
    m=[i for i in l if(i==n)]
    c=0
    for i in m:
        print(i)
        c+=1
    print(c)
    b=LeaveApplication.objects.all()
    d=0
    for i in b[:len(b) - 1]:
        print(i)

        if (i.key == None):
            continue
        else:
            print(i.key.desig)
            if (i.key.desig == n):
                d += 1
    print(d)
    e = (d * 100) / c
    print(e)
    j=LeavePercentage.objects.all()
    for i in j:
        x=i.leave_percent
        if (e >= x):
            n = request.user.username
            for i in b:
                if (i.key == None):
                    continue
                else:
                    if (i.key.user.username == n):
                        userid = i.id
            LeaveApplication.objects.get(id=userid).delete()
            return redirect('/suggest')
        else:

            n = request.user.username
            for i in b:
                if (i.key == None):
                    continue
                else:
                    if (i.key.user.username == n):
                        userid = i.id
            l = LeaveApplication.objects.get(id=userid)
            ss = l.start_date
            day = (l.end_date - l.start_date).days + 1
            for i in range(0, day):
                s = Person()
                s.name = n
                s.date = ss
                ss = ss + datetime.timedelta(days=1)
                s.status = "Leave"
                s.save()
            return redirect('/grant')
global f
def grant(request):
    current_user = request.user.username
    l=LeaveApplication.objects.all()
    for i  in l:
        if(i.key==None):
            continue
        else:
            if(i.key.user.username==current_user):
                f=i.id
    b=LeaveApplication.objects.get(id=f)
    x=b.start_date
    y=b.end_date
    return render(request,'leave_calendar/grant.html',{'x':x,'y':y})

def suggest(request):
    currdate = (datetime.datetime.now()).date()
    b = LeaveApplication.objects.all()
    s = set()
    for i in b:
        if (i.key == None):
            continue
        else:
            s.add(i.end_date - currdate)

    x = min(s)
    date = currdate + x
    return render(request, 'leave_calendar/leave_suggestion.html', {'date': date})


    '''current_user = ''
    if request.user.is_authenticated:
        current_user = User.objects.get(id=request.user.id).username
    a=Employee.objects.filter(desig=current_user.desig)
    c=0
    for i in a:
        c+=1
    b=LeaveApplication.objects.all()
    d=0
    for i in b:
        if(i.key.desig==request.user):
            d+=1

    e=(d*100)/c
    if(e>=50):
        return HttpResponse("<h1>you are not eligible</h1>")
    else:
        return HttpResponse("<h1>Granted</h1>")'''

leave_calendar/templates/leave_calendar/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
	 <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName&LOGO</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>

    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'register' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>
</nav>


{% block body%}
{% endblock %}
</body>
</html>

leave_calendar/templates/leave_calendar/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

leave_calendar/templates/leave_calendar/grant.html
{% extends 'leave_calendar/base.html' %}
{% block body %}
    <div class="container">
<div class="panel">
<h1> Your Leave Application is granted </h1>

<h3> Your leave start from {{ x }} to {{ y }}  </h3>


<h3>Thank You</h3>
</div></div>
{% endblock %}

leave_calendar/templates/leave_calendar/index.html
{%  extends 'scale_matrix/base.html' %}
{% block body %}



{% block content %}

{% if user.is_authenticated %}

<h2> Hey {{ e.user }} Welcome!</h2>
    <h2>{{ e.desig }}</h2>


{% else %}

 <li><a href="{% url 'Absenteeism.urls.login' %}">Login</a></li>

{% endif %}<p>


{% if form %}

<form method="POST" action="" data-validate='parsley'>
 <div class="container">
    <div class="container">
    <div class="col-sm-6">
    <div class="panel panel-default">
    <div class="panel-heading"><h3>Apply for Leave</h3></div>
    <div class="panel-body">
  {% csrf_token %}
  <table>
    {% for field in form %}
    <div class="fieldWrapper">
      {{ field.errors }}
      <p>{{ field.label_tag }} {{ field }}</p>
    </div>
    {% endfor %}
  </table>
  <input type="submit" value="Apply" class='btn btn-primary'/>
    </div>
    </div>
    </div>
    </div>
</div>
</form>

{% else %}


{% endif %}
<link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/themes/base/jquery-ui.css" type="text/css" media="all" />
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/jquery-ui.min.js" type="text/javascript"></script>
<script>
  $(function() {
  $( "#id_start_date" ).datepicker();
  $( "#id_end_date" ).datepicker();
  });
</script>

{% endblock content %}
{% endblock %}

leave_calendar/templates/leave_calendar/leave_suggestion.html
{% extends 'leave_calendar/base.html' %}
{% block body %}
    <div class="container">
<div class="panel">
<h1> You Are Not Eligible for Taking Leave </h1>

<h3> You Can take Leave after {{ date }} </h3>

<h3>Thank You</h3>
</div></div>
{% endblock %}