Absenteeism/urls.py
from django.urls import path
from Absenteeism import views
from django.contrib.auth.views import login,logout

urlpatterns = [
    #path('result/',views.result,name='result'),
    path('login/',login,{'template_name':'Absenteeism/login.html'},name='login'),
    path('logout/',logout,{'template_name':'Absenteeism/logout.html'}),
    path('register/',views.register,name='register'),
    path('profile/',views.profile,name='profile'),
    path('profile/check/',views.check,name='check'),
    path('home/',views.home,name='home'),
    path('all_attendance',views.all_att),
    
]

MIS_Project/urls.py
from django.contrib import admin
from django.urls import path,include
from MIS_Project import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Absenteeism.urls')),
    path('',include('leave_calendar.urls')),
    path('',include('scale_matrix.urls')),
    path('',include('Operator_window.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.MEDIA_ROOT)

Absenteeism/models.py
from django.db import models
from django.contrib.auth.models import  User
from datetime import date
from django.db.models.signals import post_save
from django.dispatch import receiver


STATUS=[
    ('Absent','Absent'),
    ('Present','Present'),
]
choice=[
    ('--select--','--select--'),
    ('Supervisor','Supervisor'),
    ('TeamLeader','TeamLeader'),
    ('Senior Operator','Senior Operator'),
    ('Skilled Operator','Skilled Operator'),
    ('Semi-Skilled Operator','Semi-Skilled Operator'),
    ('Un-Skilled Operator','Un-Skilled Operator'),
    ('Helper','Helper'),
    ('Trainee','Trainee'),
]

class Person(models.Model):
    name = models.CharField(max_length=10)
    date = models.DateField(("Date"), default=date.today)
    status=models.CharField(max_length=10,choices=STATUS)


    def __str__(self):
        return self.name + "     "+ str(self.date)+"      " +self.status

class Employee(models.Model):
        user = models.OneToOneField(User, on_delete=models.CASCADE)
        desig = models.CharField(choices=choice, max_length=20)

        def __str__(self):
            return str(self.user)

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Employee.objects.create(user=instance)
    instance.employee.save()

Absenteeism/forms.py
from django import forms
from django.contrib.auth import authenticate
class LoginForm(forms.Form):
    username=forms.CharField(max_length=15)
    password=forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        user=self.cleaned_data.get("username")
        passw=self.cleaned_data.get("password")
        usern=authenticate(username=user,password=passw)
        if usern is None:
            raise forms.ValidationError("wrong credentials")


from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError
from .models import Person
choice=[
    ('--select--','--select--'),
    ('Supervisor','Supervisor'),
    ('TeamLeader','TeamLeader'),
    ('Senior Operator','Senior Operator'),
    ('Skilled Operator','Skilled Operator'),
    ('Semi-Skilled Operator','Semi-Skilled Operator'),
    ('Un-Skilled Operator','Un-Skilled Operator'),
    ('Helper','Helper'),
    ('Trainee','Trainee'),
]


class CustomUserCreationForm(forms.Form):

    username = forms.CharField(label='Enter Username', min_length=4, max_length=150)
    first_name=forms.CharField(label='Enter Firstname', min_length=4, max_length=150)
    last_name = forms.CharField(label='Enter Lastname', min_length=4, max_length=150)
    email = forms.EmailField(label='Enter email')
    password1 = forms.CharField(label='Enter password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)
    desig=forms.ChoiceField(label='Designation',choices=choice)

    class Meta:
        model=User
        fields={'username','first_name','last_name','e-mail','password1','password2','desig'}


    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise  ValidationError("Username already exists")
        return username

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise  ValidationError("Email already exists")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise ValidationError("Password don't match")

        return password2


    def save(self, commit=True):
        user = User.objects.create_user(
            self.cleaned_data['username'],
            email=self.cleaned_data['email'],
            password=self.cleaned_data['password1'],
            first_name=self.cleaned_data['first_name'],
            last_name=self.cleaned_data['last_name'],
        )
        return user

CHOICES=[('Absent','Absent'),
         ('Present','Present'),
         ('Leave','Leave')
]
class ABC(forms.Form):
    #date =forms.DateField(witxt=forms.CharField()
    Date = forms.DateField(widget = forms.SelectDateWidget)
    Status = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect())

'''def __init__(self, request,*args, **kwargs):

        if not request.user.is_superuser:
            self.fields['Status'].widget.disabled_choices = [3]
        super().__init__(*args, **kwargs)'''

NAMES=[('Any','Any'),
    ('at','at'),
        ('intern','intern'),
       ('ravi','ravi'),
]
class QueryForm(forms.Form):
    name=forms.ModelChoiceField(User.objects.all())
    #name=forms.ChoiceField(choices=User,required=True,label="Names")
    start_date = forms.DateField(required=True,label="Start Date",widget = forms.SelectDateWidget())
    end_date = forms.DateField(required=True,label="Start Date",widget = forms.SelectDateWidget())


import django_tables2 as tables

'''class SimpleTable(tables.Table):
    class Meta:
        model = Person'''

Absenteeism/views.py
from django.shortcuts import render,redirect
from django.views.generic import TemplateView
from django.shortcuts import render
from django.contrib.auth import authenticate
from Absenteeism.forms import CustomUserCreationForm
from .forms import CustomUserCreationForm
from django.contrib import messages
from .models import Person
from .forms import LoginForm,ABC
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.http import JsonResponse
from django.views.generic import View
from rest_framework.views import APIView
from rest_framework.response import Response
from django.db.models import Avg, Count, Max, Min, Sum
from .forms import QueryForm
import datetime
from django.contrib.auth.decorators import login_required

# Create your views here.
def loginpage(request):
    myform=LoginForm(request.POST or None)
    if myform.is_valid():
        usern=myform.cleaned_data.get("username")
        passw=myform.cleaned_data.get("password")
        user=authenticate(username=usern,password=passw)
        if user:
            return redirect("/profile")
        else:
            messages.error(request, "Error")
    return render(request,"Absenteeism/login.html",{"form":myform})

def register(request):
    if (request.method=='POST'):
        form =CustomUserCreationForm(request.POST)
        if (form.is_valid()):
            user=form.save()
            user.refresh_from_db()
            user.employee.desig=form.cleaned_data['desig']
            user.save()
            return redirect('/login')
        else:
            messages.error(request, "Error")
    else:
        form= CustomUserCreationForm()

    args={'form':form}
    return render(request,'Absenteeism/signup.html',args)

@login_required
def profile(request):
    if (request.method == 'POST'):
        form = ABC(request.POST)
        if (form.is_valid()):

            obj = Person()
            obj.name = User.objects.get(id=request.user.id).username
            obj.date = form.cleaned_data['Date']
            obj.status = form.cleaned_data['Status']
            a = Person.objects.all().filter(name=request.user.username)
            t = str(obj.date)
            c = 0
            for i in a:
                if (str(i.date) == t):
                    c = c + 1
            if (c == 0):
                obj.save()
                return redirect('/profile/check')
            else:
                c = 0
                return redirect('/profile')


        else:
            messages.error(request, "Error")
    else:
        form = ABC()
        return render(request,'Absenteeism/profile.html',{'form':form})

    args={'user':request.user}
    return render(request,'Absenteeism/profile.html',args)

def check(request):
    a=Person.objects.all().filter(name=request.user.username)
    l=[]
    k=[]
    for i in a:
        l.append((i.date))
        k.append(i.status)

    return render(request,'Absenteeism/check.html',{'data':l,'status':k})
	
	
	
def home(request):
    if request.method == 'POST':
        query_form = QueryForm(request.POST)
        if(query_form.is_valid()):
            clean_query = query_form.cleaned_data
            name=clean_query['name']
            start_date = clean_query['start_date']
            end_date = clean_query['end_date']
            global start_date_str
            start_date_str = helper_start_date(start_date)
            global end_date_str
            end_date_str = helper_end_date(end_date)
            min_date_str = helper_min_date()
            max_date_str = helper_max_date()
            total_hhs = helper_total_hhs(min_date_str, max_date_str)
            brand_list = helper_get_brands()
            average_list=find_average(name)
            context={'name':name,'start_date':start_date_str,'end_date':end_date_str, 'min_date':min_date_str,
                                'max_date':max_date_str,'total_hhs':total_hhs,'brand_list':brand_list,'average':average_list}
            return render(request,'Absenteeism/result.html',context)
            #return redirect('/result')

    else:
        query_form = QueryForm()
        return render(request, 'Absenteeism/home.html', {'query_form': query_form})
		
		
		

##def result(request):
##    return render(request,'Absenteeism/result.html')

    
# ------------ BEGIN HELPER FUNCTIONS ------------ #

def helper_start_date(start_date):
	'''Takes in a datetime object, which may either be typecast from a user-supplied 
	date string or the earliest date found in the data table. Returns the date as a string.'''
	if not start_date:
		start_date_obj = Person.objects.all().aggregate(Min('date'))
		start_date = start_date_obj['date__min']
	else:
		start_date = start_date

	return(start_date)
    

def helper_end_date(end_date):
	'''Takes in a datetime object, which may either be typecast from a user-supplied 
	date string or the latest date found in the data table. Returns the date as a string.'''

	if not end_date:
		end_date_obj = Person.objects.all().aggregate(Max('date'))
		end_date = end_date_obj['date__max']
	else:
		end_date = end_date

	return(end_date)


def helper_min_date():
	'''Does not require an input. Returns the earliest date in the data table.'''

	min_date_obj = Person.objects.all().aggregate(Min('date'))
	min_date_str = min_date_obj['date__min']

	return(min_date_str)


def helper_max_date():
	'''Does not require an input. Returns the latest date in the data table.'''

	max_date_obj = Person.objects.all().aggregate(Max('date'))
	max_date_str = max_date_obj['date__max']

	return(max_date_str)


def helper_total_hhs(min_date, max_date):
	'''Takes in the earliest and latest dates found in the data table.
	Returns the count of distinct households that shopped during that period.'''

	total_hhs = Person.objects.values('name').distinct().count()
	total_hhs = "{:,}".format(total_hhs)
	return(total_hhs)

def helper_get_brands():
	'''Takes in a start date and an end date. If dates are not
	supplied by the user, the earliest and latest dates in the
	table are used. Returns a list of brands purchased within
	the dates specified.'''

	all_brands_qs = Person.objects.filter().values('name').distinct()
	brand_list = []

	for brand in all_brands_qs:
		brand_list.append(brand['name'])

	return(brand_list)


def find_average(n):
    a=Person.objects.filter(name=n)
    c=0
    for i,j in enumerate(a):
        if(j.status=='Absent'):
            c+=1
    i=i+1
    return c/i*100

'''


def top_buying_brand(brands, start_date, end_date):
##	Takes in a list of all brands in the data table, 
##	and start and end dates. Dates are selected by the user, 
##	or the largest available timeframe is used by default. 
##	Returns the average dollars spent per household on each 
##	brand within the timeframe given.

	avg_spend_hh_by_brand = {}

	for brand in brands:

		sum_item_spend = Person.objects.values('brand').filter(date__gte=start_date, 
							date__lte=end_date, brand=brand).annotate(total_spent=Sum('item_spend'))
		
		sum_hhs = Trips.objects.filter(brand=brand,date__gte=start_date,
							date__lte=end_date).values('user_id').distinct().count()
		
		avg_spend_hh = round((sum_item_spend[0]['total_spent'] / sum_hhs), 2)
		
		avg_spend_hh_by_brand[brand] = [avg_spend_hh,"{:,}".format(sum_item_spend[0]['total_spent']), "{:,}".format(sum_hhs)]

	print(avg_spend_hh_by_brand)
	return(avg_spend_hh_by_brand)




'''

def all_att(request):
    x=[]
    y=[]
    z=[]
    m=Person.objects.all()
    #table=SimpleTable(m)
    return render(request, 'Absenteeism/check_attendance.html',{'x':x,'y':y,'z':z,'m':m})

Absenteeism/templates/Absenteeism/check.html
{% extends 'Absenteeism/master.html' %}
{% block body %}
    <h1>Calendar View</h1>
    <div style="margin-left: 20%;">
    <h1>{{ user.first_name}}
    {{ user.last_name }}</h1>
    <table border="5" class="table-condensed">

       <tr>
           <td width="30%" align="center">
           {%  for i in data%}
       <h2>{{ i }}</h2>
              {% endfor %}
           </td>

    <td width="30%" style="margin-left: 10%;" align="center">
        {% for j in status %}
            <h1>{{ j }}</h1>
        {% endfor %}</td>

       </tr>

    </table></div>
{% endblock %}

Absenteeism/templates/Absenteeism/check_attendance.html
{% extends 'Absenteeism/master.html' %}

{% block body %}


<table class="table table-bordered table-striped table-hover table-responsive" >
<thead class="thead-dark">
<tr  class="btn-primary"><th style="text-align: center;">Name</th ><th style="text-align: center;">Date</th><th style="text-align: center;">Status</th></tr></thead>
   {% for i in m %}
       <tr style="text-align: center">
<td >{{ i.name}}</td>
       <td>{{ i.date }}</td>
       <td>{{ i.status }}</td>
       </tr>
{% endfor %}
</table>


{% endblock %}

Absenteeism/templates/Absenteeism/home.html
{% extends 'Absenteeism/master.html' %}


{% block body %}

<h1>Your Query Form</h1>
<form action="#" method="post">
<div class="container">
	<div class="container">
    <div class="container">
    <div class="col-sm-6">
    <div class="panel panel-default">
    <div class="panel-heading"><h3>Search Your Attendance Query</h3></div>
    <div class="panel-body">

{% csrf_token %}
	
{{ query_form.as_p }}
	<input type="submit" value="Submit" />
</div>
    </div>
    </div>
    </div>
</div>
</div>
</form>


{% endblock %}

Absenteeism/templates/Absenteeism/login.html
{% extends 'Absenteeism/master.html' %}
{% block title %}Login{% endblock %}

{% block body %}
    <div class="container">
    <div class="container">
    <div class="col-sm-6">
    <div class="panel panel-default">
    <div class="panel-heading"><h3>Login</h3></div>
    <div class="panel-body">

    <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token%}
    {% for field in form %}
        <span class="danger">{{ field.errors }}</span><br><br>
        <label>{{ field.label_tag }}</label>
        {{ field }}
    {% endfor %}
    <br><br>
    <button type="submit" class="btn btn-primary" value="SignIn" style="margin-left: 32%">submit</button>
    </form>
    <script>
    {% if messages %}
                {% for message in messages %}
                    alert(message);
                {% endfor %}
            {% endif %}
    </script>
    </div>
    </div>
    </div>
    </div>
</div>
{% endblock %}

Absenteeism/templates/Absenteeism/logout.html
{% extends 'Absenteeism/master.html' %}
{% block body %}
<h2>Your session is out!</h2>
{% endblock %}

Absenteeism/templates/Absenteeism/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
	 <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName&LOGO</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>

    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'register' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>
</nav>
  

{% block body%}
{% endblock %}
</body>
</html>

Absenteeism/templates/Absenteeism/profile.html
{% extends 'Absenteeism/master.html' %}
{% block body %}
    <div align="right">
        <a href="logout.html"> <p class="btn btn-primary" style="margin-right: 3%; margin-top: -2%">Logout</p></a>
    </div>
    <div class="container" style="margin-left: 20%;">
    <h1>Profile</h1>
	<p>
	{{ user.first_name }}
	{{ user.last_name }}
        <form method="post">

        <div class="container">
    <div class="container">
    <div class="col-sm-6">
    <div class="panel panel-default">
    <div class="panel-heading"><h3>Pay your Attendance</h3></div>
    <div class="panel-body">

        <div class=" date input-group" id="datetimepicker_id_datetime">


        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit" class="btn btn-primary" style="margin-left: 60%">submit</button></div>
         </div>
    </div>
    </div>
    </div>
</div>
        </form>
<script>
    $(document).ready(function() {
    $("#id_Status input[value='Leave']").attr("disabled","disabled");});
</script>
<script>(function () {

$(document).ready(function() {

$("#id_datetime").datetimepicker();
});
})(jQuery);
</script>


	</p>
    </div>
{% endblock %}

Absenteeism/templates/Absenteeism/result.html
{% extends 'Absenteeism/master.html' %}


{% block body %}

 <nav class="navbar navbar-inverse">
		    <div class="container-fluid">
		        <div class="navbar-header">
		            <a class="navbar-brand" href="#">Insights Dashboard</a>
		        </div>

		        <ul class="nav navbar-nav navbar-right">
		            <li><a href=" {% url 'home' %}"><button type="button" class="btn btn-primary">Search Again</button></a></li>
		        </ul>
		    </div>
		</nav>

<div class="main-content">

<div class="row" id="search-parameters">
	    	<h3>Your Search Parameters</h3>

<button type="button" class="btn btn-outline-primary">Total</button>

<button type="button" class="btn btn-outline-primary">{{ name }}</button>
<button type="button" class="btn btn-outline-primary">{{ start_date }}</button>

<button type="button" class="btn btn-outline-primary">{{ end_date }}</button>

</div><br><br>

		<div class="row" id="household-counts">

<h3>Total Attendance</h3>
	       <p> between {{ min_date }} and {{ max_date }} (largest available date range).</p>

	        	

	    </div> <!-- End of household-counts -->



<br><br><br>

<div class="row" id="household-spending">



<h5>For the period {{ start_date }} through {{ end_date }}</h5><br>
<h2> The Total Average Percentage of {{ name }} is {{ average }}</h2>
     <style>
	    	body {
    			font-family: 'Montserrat';
			}

			.btn-outline-primary {
				border-color: #FF7011;
				color: #25303B;
				pointer-events: none;
			}

			.btn-primary {
				background-color: #FF7011;
				border-color: #FF7011;
				border-radius: 10px;
				font-size: 1.2em;
			}

			h3 {
				font-weight: bold;
				color: #25303B;
			}

			h5 {
				font-family: 'Montserrat';
			}

			.main-content {
				padding-left: 50px;
				padding-top: 15px;
    			padding-bottom: 50px;

			}

			.navbar-brand {
				font-size: 1.75em;
				font-color: white;
				font-weight: bold;
				padding-top: 25px;
				pointer-events: none;
			}

			.navbar-inverse {
				background-color: #25303B;
				border-radius: 0px
			}

			.navbar-right {
				padding-right: 20px;
			}

			table, th, td {
    			border: 1px solid #DCDCDC;
			}

			th {
				font-size: 1.05em;
				background-color: #E9E9E9;
			}

			th, td {
				padding: 5px;
			}
	    </style>
{% endblock %}

 

Absenteeism/templates/Absenteeism/signup.html
{% extends 'Absenteeism/master.html' %}
{% block body %}
    <div class="container">
    <div class="panel panel-default">
    <div class="panel-heading"><h2>Registration</h2></div>
    <div class="panel-body">

<form method="post">
    {% csrf_token %}
    {{  form.as_p }}
    <button type="submit" class="btn btn-primary" value="Signup" style="margin-left: 20%">submit</button>
</form>
    <script>
    {% if messages %}
                {% for message in messages %}
                    alert(message);
                {% endfor %}
            {% endif %}
    </script>

    </div>
    </div>
    </div>
{% endblock %}